kind: Service
apiVersion: v1
metadata:
  name: my-spring-service-aayushi
spec:
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  selector:
    app: my-spring-container
  type: LoadBalancer
